// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Fine Edge",
    "description": "Fine Edge"
  },

  "Footer": {
    "links": {
      "link-1": "Services",
      "link-2": "About us",
      "link-3": "Blog",
      "link-4": "Contact us"
    },

    "copyright": "All rights reserved."
  },

  "Blog": {
    "title": "Blog",
    "read-more": "Read more",
    "not-found": "No articles are currently available",

    "post": {
      "return": "Return to the blog",
      "not-found": "The article does not exist."
    },

    "close": "Close"
  }
};
export default messages;