// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Fine Edge",
    "description": "Fine Edge"
  },

  "Footer": {
    "links": {
      "link-1": "Services",
      "link-2": "About us",
      "link-3": "Blog",
      "link-4": "Contact us"
    },

    "copyright": "All rights reserved."
  }
};
export default messages;