// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Fine Edge",
    "description": "Fine Edge"
  }
};
export default messages;